
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-01-26 10:32:28.126345
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
faultd_BASEDIR := $(BASEDIR)faultd


ALL_MODULES := $(ALL_MODULES) faultd
